os: linux
dist: xenial
addons:
  apt:
    packages:
      - docker-ce
      - python3
sudo: required
language: csharp
mono: none
env: DOTNETCORE=1
dotnet: 3.1
services:
  - docker
script:
  - chmod +x ./deploy-envs.sh
  - chmod +x ./scripts/build.sh
  - chmod +x ./scripts/deploy.sh
  - cd scripts && ./build.sh
  - if [ "$TRAVIS_BRANCH" == "master" ]; then ./deploy.sh; fi