version: '3.4'

services:
  api:
    container_name: personal
    image: personal-api:latest
    build:
      context: .
    env_file: .env
    expose:
      - "5000"
  reverseproxy:
    build:
      context: ./Personal.ReverseProxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - api